### ISSUE TITLE
Hevon Family Application

### ISSUE THREAD

**Issue by Maki776** [RoyaleAPI/family-config#1021] opened 2024-02-06 00:36 UTC

**Comment by Maki776** [comment] 2024-02-06 00:36
name: Hevon
key: Hevon
color: blue
emblem: heart_04
info:
  description: >
    The **Hevon Clan Family** is a war family, consisting of 6 clans. Players are involved in Discord and CR activities!
  social:
    - discord: https://discord.gg/qsxKepCM3z
clans:
  - name: GrannyPunchers2
    tag: L9UPCUGY
  - name: TEAM KNOCKOUTS
    tag: YQJPR2V9
  - name: Indian Helix
    tag: QQRYRP8G
  - name: Hevon
    tag: GVVCUP9P
  - name: Hevie
    tag: QYPV9LPQ
  - name: Shogun
    tag: GGU29GLQ

**Comment by Zaop7** [comment] 2024-02-10 16:36
> [!note]
> Please format your request as yaml file and attach it as an code in your request. You can find the instructions [here](https://github.com/RoyaleAPI/family-config/blob/master/README.md) or take inspiration from other issues.

**Comment by Zaop7** [comment] 2024-03-05 22:42
Duplicate of #1022

**Closed as not planned by Zaop7** 2024-03-05 22:42 UTC
Labels: format_needed
